# https://github.com/realm/SwiftLint#configuration
# https://realm.github.io/SwiftLint/rule-directory.html
# swiftlint:disable <rule for rest of file>
# swiftlint:disable:next <rule on next line>
# swiftlint:disable:this <rule on next line>
disabled_rules:
  - blanket_disable_command
  - closure_parameter_position  # conflicts with swift-format
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - function_parameter_count
  - identifier_name
  - inclusive_language # was blocking masters thesis usages
  - large_tuple
  - line_length
  - mark
  - multiple_closures_with_trailing_closure
  - nesting
  - opening_brace
  - shorthand_operator # was crashing on usages of operator overloads
  - statement_position
  - switch_case_alignment
  - trailing_comma
  - trailing_whitespace
  - type_body_length
  - type_name
opt_in_rules:
  - async_without_await
  - comma_inheritance
  - convenience_type
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_assert
  #- discouraged_none_name
  - direct_return
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  #- explicit_enum_raw_value
  - expiring_todo
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  #- force_unwrapping
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  #- multiline_call_arguments
  - multiline_parameters
  #- opaque_over_existential
  - operator_usage_whitespace
  - optional_enum_case_matching
  - pattern_matching_keywords
  - period_spacing
  - prefer_key_path
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  #- private_swiftui_state
  #- raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_self
  - redundant_sendable
  - redundant_type_annotation
  - return_value_from_void_function
  - shorthand_optional_binding
  - sorted_first_last
  #- superfluous_else
  - toggle_bool
  #- trailing_closure
  - unavailable_function
  - unhandled_throwing_task
  - unneeded_escaping
  - unneeded_parentheses_in_closure_argument
  - unneeded_throws_rethrows
analyzer_rules:
  - unused_declaration
  - unused_import
excluded:
  - .build
unhandled_throwing_task:
  severity: warning
reporter: "xcode"
