upstream:
    sources:
        - repo: giginet/xcodeproj-mcp-server
          branch: main
          relationship: derived
          notes: Sources/Tools/Project/ (23 tools), Sources/Utilities/PathUtility.swift
          last_checked_sha: b29c9aae7fa57a9e65e50fa91dc55eebd1820d4b
          last_checked_date: "2026-02-18T22:08:27Z"
          paths:
            high:
                - Sources/XcodeProjectMCP/*.swift
            medium:
                - Package.swift
                - Tests/**
            low:
                - .github/**
                - Dockerfile
                - README.md
                - Documentation/**
        - repo: ldomaradzki/xcsift
          branch: master
          relationship: derived
          notes: Sources/Core/BuildOutputParser.swift, BuildOutputModels.swift, CoverageParser.swift
          last_checked_sha: 7cdf88aba7059490985c05d75955c6cefd06fe3d
          last_checked_date: "2026-02-18T22:08:27Z"
          paths:
            high:
                - Sources/OutputParser.swift
                - Sources/Models.swift
                - Sources/CoverageParser.swift
            medium:
                - Sources/Configuration.swift
                - Package.swift
                - Tests/**
            low:
                - Sources/Install/**
                - Sources/main.swift
                - .github/**
                - plugins/**
                - README.md
                - docs/**
        - repo: Ryu0118/xcstrings-crud
          branch: main
          relationship: derived
          notes: Sources/Core/XCStrings/ (7 files)
          last_checked_sha: 467982835dadd388ee6bdc62021fc252aef9a135
          last_checked_date: "2026-02-18T22:08:27Z"
          paths:
            high:
                - Sources/XCStringsKit/**
            medium:
                - Sources/XCStringsMCP/**
                - Sources/XCStringsCLI/**
                - Tests/**
            low:
                - .github/**
                - README.md
        - repo: tuist/xcodeproj
          branch: main
          relationship: dependency
          notes: All project manipulation tools via XcodeProj library
          last_checked_sha: e5e0f1b0db4d8cbaedc55d9c14bbdf48d9dfe6ca
          last_checked_date: "2026-02-20T17:04:05Z"
          paths:
            high:
                - Sources/XcodeProj/Objects/**
                - Sources/XcodeProj/Scheme/**
                - Sources/XcodeProj/Project/**
            medium:
                - Sources/XcodeProj/Utils/**
                - Sources/XcodeProj/Extensions/**
                - Package.swift
                - CHANGELOG.md
                - Tests/**
            low:
                - .github/**
                - README.md
                - Documentation/**
                - fixtures/**
                - Makefile
        - repo: getsentry/XcodeBuildMCP
          branch: main
          relationship: watch
          notes: Monitor for features worth incorporating into xc-mcp
          last_checked_sha: 124042572e3f9f59532a2eb51ee6500e7976bb3b
          last_checked_date: "2026-02-19T00:00:00Z"
          paths:
            high:
                - Sources/**/*Tool*.swift
                - Sources/**/*Handler*.swift
            medium:
                - Sources/**/*.swift
                - Package.swift
                - Tests/**
            low:
                - .github/**
                - README.md
                - Documentation/**
                - LICENSE
                - '*.md'

nope:
  rules:
    - name: git-checkout-switch
      pattern: 'git\s+(checkout|switch)\s+'
      message: "git checkout/switch not allowed — branch changes require user approval"

    - name: git-no-verify
      pattern: '--no-verify'
      message: "skipping hooks with --no-verify not allowed"

    - name: destructive-rm
      pattern: 'rm\s+(-[a-zA-Z]*f[a-zA-Z]*\s+|--force\s+).*(/|~|\$HOME)'
      message: "destructive rm on broad paths not allowed"

    - name: curl-bearer
      pattern: 'curl.*Authorization.*Bearer'
      message: "direct API calls with bearer tokens not allowed"

    - name: todo-archive
      pattern: 'todo\s+archive'
      message: "todo archive not allowed — only user should archive issues"

    # Non-Bash tool rules
    - name: no-write-env
      pattern: '"file_path"\s*:\s*"[^"]*\.env"'
      tools: ["Write", "Edit"]
      message: "writing to .env files not allowed"

    - name: no-write-credentials
      pattern: '"file_path"\s*:\s*"[^"]*(\.pem|\.key|\.p12|credentials\.json)"'
      tools: ["Write", "Edit"]
      message: "writing to credential files not allowed"

todo:
  path: .issues
  default_status: ready
  default_type: task
  sync:
      github:
          repo: toba/xc-mcp
