import Foundation

// MARK: - Core Data Structures

/// Root structure of xcstrings file
public struct XCStringsFile: Codable, Sendable {
    public var sourceLanguage: String
    public var strings: [String: StringEntry]
    public var version: String

    public init(
        sourceLanguage: String = "en",
        strings: [String: StringEntry] = [:],
        version: String = "1.0",
    ) {
        self.sourceLanguage = sourceLanguage
        self.strings = strings
        self.version = version
    }
}

/// String entry for each key
public struct StringEntry: Codable, Sendable {
    public var comment: String?
    public var isCommentAutoGenerated: Bool?
    public var extractionState: String?
    public var shouldTranslate: Bool?
    public var localizations: [String: Localization]?

    /// `false` only when the entry is explicitly marked non-translatable in Xcode (Localization
    /// Properties → "Should Translate" off).
    public var requiresTranslation: Bool { shouldTranslate != false }

    public init(
        comment: String? = nil,
        isCommentAutoGenerated: Bool? = nil,
        extractionState: String? = nil,
        shouldTranslate: Bool? = nil,
        localizations: [String: Localization]? = nil,
    ) {
        self.comment = comment
        self.isCommentAutoGenerated = isCommentAutoGenerated
        self.extractionState = extractionState
        self.shouldTranslate = shouldTranslate
        self.localizations = localizations
    }
}

/// Localization entry
public struct Localization: Codable, Sendable {
    public var stringUnit: StringUnit?
    public var variations: Variations?

    public init(stringUnit: StringUnit? = nil, variations: Variations? = nil) {
        self.stringUnit = stringUnit
        self.variations = variations
    }
}

/// String unit containing the actual translation value
public struct StringUnit: Codable, Sendable {
    public var state: String
    public var value: String

    public init(state: String = "translated", value: String) {
        self.state = state
        self.value = value
    }
}

/// Variations (plural, device, etc.)
public struct Variations: Codable, Sendable {
    public var plural: PluralVariation?
    public var device: DeviceVariation?

    public init(plural: PluralVariation? = nil, device: DeviceVariation? = nil) {
        self.plural = plural
        self.device = device
    }
}

/// Wrapper for a variation category value.
///
/// In xcstrings JSON, each variation value is
/// `{ "stringUnit": { "state": "...", "value": "..." } }`.
public struct VariationValue: Codable, Sendable {
    public var stringUnit: StringUnit?

    public init(stringUnit: StringUnit? = nil) { self.stringUnit = stringUnit }
}

/// Plural variation
public struct PluralVariation: Codable, Sendable {
    public var zero: VariationValue?
    public var one: VariationValue?
    public var two: VariationValue?
    public var few: VariationValue?
    public var many: VariationValue?
    public var other: VariationValue?

    public init(
        zero: VariationValue? = nil,
        one: VariationValue? = nil,
        two: VariationValue? = nil,
        few: VariationValue? = nil,
        many: VariationValue? = nil,
        other: VariationValue? = nil,
    ) {
        self.zero = zero
        self.one = one
        self.two = two
        self.few = few
        self.many = many
        self.other = other
    }
}

/// Device variation
public struct DeviceVariation: Codable, Sendable {
    public var iphone: VariationValue?
    public var ipad: VariationValue?
    public var mac: VariationValue?
    public var applewatch: VariationValue?
    public var appletv: VariationValue?

    public init(
        iphone: VariationValue? = nil,
        ipad: VariationValue? = nil,
        mac: VariationValue? = nil,
        applewatch: VariationValue? = nil,
        appletv: VariationValue? = nil,
    ) {
        self.iphone = iphone
        self.ipad = ipad
        self.mac = mac
        self.applewatch = applewatch
        self.appletv = appletv
    }
}

// MARK: - Output Models

/// Key information for output
public struct KeyInfo: Codable, Sendable {
    public let key: String
    public let comment: String?
    public let isCommentAutoGenerated: Bool?
    public let extractionState: String?
    public let shouldTranslate: Bool?
    public let languages: [String]

    public init(
        key: String,
        comment: String?,
        isCommentAutoGenerated: Bool? = nil,
        extractionState: String?,
        shouldTranslate: Bool? = nil,
        languages: [String]
    ) {
        self.key = key
        self.comment = comment
        self.isCommentAutoGenerated = isCommentAutoGenerated
        self.extractionState = extractionState
        self.shouldTranslate = shouldTranslate
        self.languages = languages
    }
}

/// Translation information for output
public struct TranslationInfo: Codable, Sendable {
    public let key: String
    public let language: String
    public let value: String?
    public let state: String?
    public let hasVariations: Bool

    public init(
        key: String,
        language: String,
        value: String?,
        state: String?,
        hasVariations: Bool,
    ) {
        self.key = key
        self.language = language
        self.value = value
        self.state = state
        self.hasVariations = hasVariations
    }
}

/// Coverage information for output
public struct CoverageInfo: Codable, Sendable {
    public let key: String
    public let translatedLanguages: [String]
    public let missingLanguages: [String]
    public let coveragePercent: Double

    public init(
        key: String,
        translatedLanguages: [String],
        missingLanguages: [String],
        coveragePercent: Double,
    ) {
        self.key = key
        self.translatedLanguages = translatedLanguages
        self.missingLanguages = missingLanguages
        self.coveragePercent = coveragePercent
    }
}

/// Overall statistics for output
public struct StatsInfo: Codable, Sendable {
    public let totalKeys: Int
    public let sourceLanguage: String
    public let languages: [String]
    public let coverageByLanguage: [String: LanguageStats]

    public init(
        totalKeys: Int,
        sourceLanguage: String,
        languages: [String],
        coverageByLanguage: [String: LanguageStats],
    ) {
        self.totalKeys = totalKeys
        self.sourceLanguage = sourceLanguage
        self.languages = languages
        self.coverageByLanguage = coverageByLanguage
    }
}

/// Per-language statistics
public struct LanguageStats: Codable, Sendable {
    public let translated: Int
    public let untranslated: Int
    public let total: Int
    public let coveragePercent: Double

    public init(translated: Int, untranslated: Int, total: Int, coveragePercent: Double) {
        self.translated = translated
        self.untranslated = untranslated
        self.total = total
        self.coveragePercent = coveragePercent
    }
}

/// Token-efficient batch coverage summary for multiple files
public struct BatchCoverageSummary: Codable, Sendable {
    public let files: [FileCoverageSummary]
    public let aggregated: AggregatedCoverage

    public init(files: [FileCoverageSummary], aggregated: AggregatedCoverage) {
        self.files = files
        self.aggregated = aggregated
    }
}

/// Compact coverage summary for a single file
public struct FileCoverageSummary: Codable, Sendable {
    public let file: String
    public let totalKeys: Int
    public let languages: [String: Double]

    public init(file: String, totalKeys: Int, languages: [String: Double]) {
        self.file = file
        self.totalKeys = totalKeys
        self.languages = languages
    }
}

/// Aggregated coverage across all files
public struct AggregatedCoverage: Codable, Sendable {
    public let totalFiles: Int
    public let totalKeys: Int
    public let averageCoverageByLanguage: [String: Double]

    public init(totalFiles: Int, totalKeys: Int, averageCoverageByLanguage: [String: Double]) {
        self.totalFiles = totalFiles
        self.totalKeys = totalKeys
        self.averageCoverageByLanguage = averageCoverageByLanguage
    }
}

// MARK: - Untranslated Check Models

/// Reason a key is flagged as untranslated for a given language.
///
/// Ported from Ryu0118/xcstrings-crud PR #33 — provides a structured signal beyond "key is missing"
/// so callers can distinguish e.g. an empty string, a `needs_review` state, and partial
/// plural/device variation coverage.
public enum UntranslatedReason: String, Codable, Sendable {
    /// No localization entry exists for the language at all.
    case missingLocalization = "missing_localization"
    /// Localization exists but has no `stringUnit` and no `variations`.
    case missingStringUnit = "missing_string_unit"
    /// `stringUnit` exists but `value` is an empty string.
    case emptyValue = "empty_value"
    /// `stringUnit.state` is not `"translated"` (e.g. `new`, `needs_review`, `stale`).
    case stateNotTranslated = "state_not_translated"
    /// `variations` exists but contains no values for any variant.
    case missingVariationValues = "missing_variation_values"
    /// A variation has no `stringUnit`.
    case missingVariationStringUnit = "missing_variation_string_unit"
    /// A variation's `stringUnit.value` is empty.
    case emptyVariationValue = "empty_variation_value"
    /// A variation's `stringUnit.state` is not `"translated"`.
    case variationStateNotTranslated = "variation_state_not_translated"
}

/// One detected untranslated entry. `state` is the `stringUnit.state` when available (otherwise
/// `nil`).
public struct UntranslatedIssue: Codable, Sendable {
    public let key: String
    public let language: String
    public let reason: UntranslatedReason
    public let state: String?

    public init(key: String, language: String, reason: UntranslatedReason, state: String?) {
        self.key = key
        self.language = language
        self.reason = reason
        self.state = state
    }
}

/// Aggregate result of an untranslated check across one file × N languages.
public struct UntranslatedCheckResult: Codable, Sendable {
    public let file: String
    public let issues: [UntranslatedIssue]
    public let issueCount: Int

    public init(file: String, issues: [UntranslatedIssue]) {
        self.file = file
        self.issues = issues
        issueCount = issues.count
    }
}

// MARK: - Stale Key Models

/// Result of listing stale keys in a single file
public struct StaleKeysResult: Codable, Sendable {
    public let file: String
    public let staleKeys: [String]
    public let count: Int

    public init(file: String, staleKeys: [String]) {
        self.file = file
        self.staleKeys = staleKeys
        count = staleKeys.count
    }
}

/// Summary of stale keys across multiple files
public struct BatchStaleKeysSummary: Codable, Sendable {
    public let files: [StaleKeysResult]
    public let totalStaleKeys: Int

    public init(files: [StaleKeysResult]) {
        self.files = files
        totalStaleKeys = files.reduce(0) { $0 + $1.count }
    }
}

// MARK: - Batch Check Models

/// Result of checking multiple keys for existence
public struct BatchCheckKeysResult: Codable, Sendable {
    public let results: [String: Bool]
    public let existCount: Int
    public let missingCount: Int

    public init(results: [String: Bool]) {
        self.results = results
        existCount = results.values.filter(\.self).count
        missingCount = results.values.count(where: { !$0 })
    }
}

// MARK: - Batch Write Models

/// Entry for a batch translation operation
public struct BatchTranslationEntry: Codable, Sendable {
    public let key: String
    public let translations: [String: String]

    public init(key: String, translations: [String: String]) {
        self.key = key
        self.translations = translations
    }
}

/// Result of a batch write operation
public struct BatchWriteResult: Codable, Sendable {
    public let succeeded: Int
    public let errors: [BatchWriteError]

    public init(succeeded: Int, errors: [BatchWriteError]) {
        self.succeeded = succeeded
        self.errors = errors
    }
}

/// Individual error from a batch write operation
public struct BatchWriteError: Codable, Sendable {
    public let key: String
    public let error: String

    public init(key: String, error: String) {
        self.key = key
        self.error = error
    }
}

// MARK: - Promote Literal Models

/// A request to promote a hand-typed localizable literal to a reusable manual catalog key.
public struct PromoteLiteralRequest: Sendable {
    /// The source-language literal text (e.g. `"Cancel"`).
    public let value: String
    /// Explicit `SCREAMING_SNAKE` key. When `nil`, one is derived from `value`.
    public let key: String?
    /// Optional developer comment stored on the entry.
    public let comment: String?

    public init(value: String, key: String? = nil, comment: String? = nil) {
        self.value = value
        self.key = key
        self.comment = comment
    }
}

/// Outcome of promoting a single literal.
public enum PromotedLiteralStatus: String, Codable, Sendable { case created, reused, collision }

/// Result of promoting one literal, including the Swift symbol Xcode will generate for the key.
public struct PromotedLiteral: Codable, Sendable {
    public let value: String
    public let key: String
    public let symbol: String
    /// Full generated member signature when the value is parameterized (has format placeholders),
    /// e.g. `addCitationToGroup(ordinal: String)`. `nil` for plain values, whose member is a
    /// property called as `.symbol`.
    public let signature: String?
    public let status: PromotedLiteralStatus
    public let message: String?

    public init(
        value: String,
        key: String,
        symbol: String,
        signature: String? = nil,
        status: PromotedLiteralStatus,
        message: String? = nil,
    ) {
        self.value = value
        self.key = key
        self.symbol = symbol
        self.signature = signature
        self.status = status
        self.message = message
    }

    /// Build a result, deriving `symbol` and `signature` for the value from `key` so every
    /// outcome (created / reused / collision) reports them consistently.
    public init(
        value: String,
        key: String,
        status: PromotedLiteralStatus,
        message: String? = nil,
    ) {
        self.init(
            value: value,
            key: key,
            symbol: LocalizableKeyNaming.generatedSymbol(forKey: key),
            signature: LocalizableKeyNaming.generatedSignature(forKey: key, value: value),
            status: status,
            message: message,
        )
    }
}

/// Aggregate result of a promote-literals operation.
public struct PromoteLiteralsResult: Codable, Sendable {
    public let file: String
    public let promoted: [PromotedLiteral]
    public let createdCount: Int
    public let reusedCount: Int
    public let collisionCount: Int

    public init(file: String, promoted: [PromotedLiteral]) {
        self.file = file
        self.promoted = promoted
        createdCount = promoted.count(where: { $0.status == .created })
        reusedCount = promoted.count(where: { $0.status == .reused })
        collisionCount = promoted.count(where: { $0.status == .collision })
    }
}

// MARK: - Compact Output Models (100% languages omitted)

/// Compact stats info - only shows languages under 100%
public struct CompactStatsInfo: Codable, Sendable {
    public let totalKeys: Int
    public let sourceLanguage: String
    public let totalLanguages: Int
    public let allComplete: Bool
    public let incompleteLanguages: [String: LanguageStats]?
    public let completeCount: Int

    public init(from stats: StatsInfo) {
        totalKeys = stats.totalKeys
        sourceLanguage = stats.sourceLanguage
        totalLanguages = stats.languages.count

        let incomplete = stats.coverageByLanguage.filter { $0.value.coveragePercent < 100 }
        allComplete = incomplete.isEmpty
        incompleteLanguages = incomplete.isEmpty ? nil : incomplete
        completeCount = stats.coverageByLanguage.count - incomplete.count
    }
}

/// Compact file coverage summary - only shows languages under 100%
public struct CompactFileCoverageSummary: Codable, Sendable {
    public let file: String
    public let totalKeys: Int
    public let totalLanguages: Int
    public let allComplete: Bool
    public let incompleteLanguages: [String: Double]?
    public let completeCount: Int

    public init(from summary: FileCoverageSummary) {
        file = summary.file
        totalKeys = summary.totalKeys
        totalLanguages = summary.languages.count

        let incomplete = summary.languages.filter { $0.value < 100 }
        allComplete = incomplete.isEmpty
        incompleteLanguages = incomplete.isEmpty ? nil : incomplete
        completeCount = summary.languages.count - incomplete.count
    }
}

/// Compact batch coverage summary
public struct CompactBatchCoverageSummary: Codable, Sendable {
    public let files: [CompactFileCoverageSummary]
    public let aggregated: CompactAggregatedCoverage

    public init(from batch: BatchCoverageSummary) {
        files = batch.files.map { CompactFileCoverageSummary(from: $0) }
        aggregated = CompactAggregatedCoverage(from: batch.aggregated)
    }
}

/// Compact aggregated coverage
public struct CompactAggregatedCoverage: Codable, Sendable {
    public let totalFiles: Int
    public let totalKeys: Int
    public let totalLanguages: Int
    public let allComplete: Bool
    public let incompleteLanguages: [String: Double]?
    public let completeCount: Int

    public init(from agg: AggregatedCoverage) {
        totalFiles = agg.totalFiles
        totalKeys = agg.totalKeys
        totalLanguages = agg.averageCoverageByLanguage.count

        let incomplete = agg.averageCoverageByLanguage.filter { $0.value < 100 }
        allComplete = incomplete.isEmpty
        incompleteLanguages = incomplete.isEmpty ? nil : incomplete
        completeCount = agg.averageCoverageByLanguage.count - incomplete.count
    }
}
