import Foundation
import Testing
@testable import XCMCPCore

/// Regression coverage for behaviors ported from
/// https://github.com/Ryu0118/xcstrings-crud:
/// - `shouldTranslate: false` excludes entries from translation accounting
///   (commit 9803d77, jig oh0-b83)
/// - `isCommentAutoGenerated` survives a save/load round trip
///   (commit 716078a, jig azt-qxr)
/// - String keys are sorted with `localizedStandardCompare` and serialized
///   in Xcode's on-disk format (commit 84ae167, jig 21p-lqj)
/// - Forward slashes are not escaped in encoder output to match Xcode
///   (commit 2380a6e, jig yzv-us5)
/// - NFKC-equivalent key suggestions surface on lookup failure
///   (commit 1384fa7, jig zyj-8ys)
struct XCStringsUpstreamPortTests {
    // MARK: - shouldTranslate

    @Test func `listUntranslated skips shouldTranslate=false`() {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "translatable": StringEntry(
                    localizations: [
                        "en": Localization(
                            stringUnit: StringUnit(state: "translated", value: "Hi")
                        ),
                    ]
                ),
                "non_translatable": StringEntry(
                    shouldTranslate: false,
                    localizations: [
                        "en": Localization(
                            stringUnit: StringUnit(state: "translated", value: "API_KEY")
                        ),
                    ]
                ),
            ]
        )

        let untranslated = XCStringsReader(file: file).listUntranslated(for: "ja")
        #expect(untranslated == ["translatable"])
    }

    @Test func `checkCoverage reports 100% for shouldTranslate=false`() throws {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "translatable": StringEntry(
                    localizations: [
                        "en": Localization(
                            stringUnit: StringUnit(state: "translated", value: "Hi")
                        ),
                        "ja": Localization(
                            stringUnit: StringUnit(state: "translated", value: "やあ")
                        ),
                    ]
                ),
                "non_translatable": StringEntry(
                    shouldTranslate: false,
                    localizations: [
                        "en": Localization(
                            stringUnit: StringUnit(state: "translated", value: "API_KEY")
                        ),
                    ]
                ),
            ]
        )
        let reader = XCStringsReader(file: file)

        let coverage = try reader.checkCoverage("non_translatable")
        #expect(coverage.coveragePercent == 100)
        #expect(coverage.missingLanguages.isEmpty)
    }

    @Test func `getStats excludes shouldTranslate=false from totals`() throws {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "a": StringEntry(localizations: [
                    "en": Localization(
                        stringUnit: StringUnit(state: "translated", value: "A")
                    ),
                    "ja": Localization(
                        stringUnit: StringUnit(state: "translated", value: "あ")
                    ),
                ]),
                "b": StringEntry(localizations: [
                    "en": Localization(
                        stringUnit: StringUnit(state: "translated", value: "B")
                    ),
                ]),
                "non_translatable": StringEntry(
                    shouldTranslate: false,
                    localizations: [
                        "en": Localization(
                            stringUnit: StringUnit(state: "translated", value: "API_KEY")
                        ),
                    ]
                ),
            ]
        )

        let stats = XCStringsStatsCalculator(file: file).getStats()
        let ja = try #require(stats.coverageByLanguage["ja"])

        // Two translatable entries; one translated to ja → 50%.
        // Without the filter this would be 1/3 ≈ 33%.
        #expect(ja.total == 2)
        #expect(ja.translated == 1)
        #expect(ja.untranslated == 1)
        #expect(ja.coveragePercent == 50)
    }

    @Test func `getKey passes shouldTranslate through`() throws {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "non_translatable": StringEntry(shouldTranslate: false),
            ]
        )

        let info = try XCStringsReader(file: file).getKey("non_translatable")
        #expect(info.shouldTranslate == false)
    }

    // MARK: - isCommentAutoGenerated

    @Test func `getKey passes isCommentAutoGenerated through`() throws {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "auto": StringEntry(
                    comment: "Auto-generated by Xcode",
                    isCommentAutoGenerated: true
                ),
            ]
        )

        let info = try XCStringsReader(file: file).getKey("auto")
        #expect(info.isCommentAutoGenerated == true)
        #expect(info.comment == "Auto-generated by Xcode")
    }

    @Test func `isCommentAutoGenerated survives save load round trip`() throws {
        let json = """
        {
          "sourceLanguage" : "en",
          "strings" : {
            "auto" : {
              "comment" : "Auto-generated by Xcode",
              "isCommentAutoGenerated" : true
            }
          },
          "version" : "1.0"
        }
        """
        let data = Data(json.utf8)

        let decoded = try JSONDecoder().decode(XCStringsFile.self, from: data)
        #expect(decoded.strings["auto"]?.isCommentAutoGenerated == true)

        let reencoded = try XCStringsFileEncoder.encode(decoded)
        let redecoded = try JSONDecoder().decode(XCStringsFile.self, from: reencoded)
        #expect(redecoded.strings["auto"]?.isCommentAutoGenerated == true)
        #expect(redecoded.strings["auto"]?.comment == "Auto-generated by Xcode")
    }

    // MARK: - Xcode-style key sort

    @Test func `keys sort with localizedStandardCompare`() {
        // Lexicographic sort would give: ["item_1", "item_10", "item_2", "item_a"]
        // Xcode's localizedStandardCompare gives natural numeric ordering:
        let sorted = XCStringsKeySorter.sort(["item_10", "item_2", "item_a", "item_1"])
        #expect(sorted == ["item_1", "item_2", "item_10", "item_a"])
    }

    @Test func `listKeys uses Xcode sort`() {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "item_10": StringEntry(),
                "item_2": StringEntry(),
                "item_1": StringEntry(),
            ]
        )

        #expect(XCStringsReader(file: file).listKeys() == ["item_1", "item_2", "item_10"])
    }

    // MARK: - Encoder format

    @Test func `encoder does not escape forward slashes`() throws {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "category": StringEntry(
                    localizations: [
                        "en": Localization(
                            stringUnit: StringUnit(
                                state: "translated",
                                value: "Domestic / Foreign"
                            )
                        ),
                    ]
                ),
            ]
        )

        let data = try XCStringsFileEncoder.encode(file)
        // sm:ignore useFailableStringInit — encoder output is always valid UTF-8.
        let json = String(decoding: data, as: UTF8.self)

        #expect(json.contains("Domestic / Foreign"))
        #expect(!json.contains("\\/"))
    }

    // MARK: - NFKC suggestions

    @Test func `suggestions returns NFKC-equivalent existing keys`() {
        // Xcode-emitted key uses RIGHT SINGLE QUOTATION MARK (U+2019).
        let xcodeKey = "Record today\u{2019}s progress"
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [xcodeKey: StringEntry()]
        )
        let reader = XCStringsReader(file: file)

        // Caller passed the visually-identical APOSTROPHE (U+0027).
        let queried = "Record today\u{0027}s progress"
        #expect(reader.suggestions(for: queried) == [xcodeKey])
    }

    @Test func `keyNotFound includes NFKC suggestions in its description`() {
        let xcodeKey = "Record today\u{2019}s progress"
        let queried = "Record today\u{0027}s progress"
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [xcodeKey: StringEntry()]
        )

        do {
            _ = try XCStringsReader(file: file).getKey(queried)
            Issue.record("Expected keyNotFound to throw")
        } catch {
            let description = error.errorDescription ?? ""
            #expect(description.contains("Did you mean"))
            #expect(description.contains(xcodeKey))
        }
    }

    @Test func `suggestions are empty when no NFKC equivalent exists`() {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: ["hello": StringEntry()]
        )
        #expect(XCStringsReader(file: file).suggestions(for: "goodbye") == [])
    }

    // MARK: - Encoder format

    @Test func `encoder emits Xcode key-colon-value format with sorted keys`() throws {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "item_10": StringEntry(comment: "ten"),
                "item_2": StringEntry(comment: "two"),
            ]
        )

        let data = try XCStringsFileEncoder.encode(file)
        // sm:ignore useFailableStringInit — encoder output is always valid UTF-8.
        let json = String(decoding: data, as: UTF8.self)

        // Xcode uses `"key" : value` (space before colon), not `"key": value`.
        #expect(json.contains("\"sourceLanguage\" : \"en\""))
        // Natural sort: item_2 must come before item_10.
        let idx2 = try #require(json.range(of: "\"item_2\""))
        let idx10 = try #require(json.range(of: "\"item_10\""))
        #expect(idx2.lowerBound < idx10.lowerBound)
        // Top-level shape: sourceLanguage, strings, version (in that order).
        let idxSrc = try #require(json.range(of: "\"sourceLanguage\""))
        let idxStrings = try #require(json.range(of: "\"strings\""))
        let idxVersion = try #require(json.range(of: "\"version\""))
        #expect(idxSrc.lowerBound < idxStrings.lowerBound)
        #expect(idxStrings.lowerBound < idxVersion.lowerBound)
    }
}
