import Testing
import Foundation
@testable import XCMCPCore

/// Regression coverage for behaviors ported from https://github.com/Ryu0118/xcstrings-crud:
/// - `shouldTranslate: false` excludes entries from translation accounting (commit 9803d77, jig
///   oh0-b83)
/// - `isCommentAutoGenerated` survives a save/load round trip (commit 716078a, jig azt-qxr)
/// - String keys are sorted in UTF-8 byte order and serialized in the on-disk format that
///   `xcstringstool` writes (commit 78b31d0, jig 9e8af79e)
/// - Forward slashes are not escaped in encoder output to match Xcode (commit 2380a6e, jig yzv-us5)
/// - NFKC-equivalent key suggestions surface on lookup failure (commit 1384fa7, jig zyj-8ys)
struct XCStringsUpstreamPortTests {
    // MARK: - shouldTranslate

    @Test func `listUntranslated skips shouldTranslate=false`() {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "translatable": StringEntry(localizations: [
                    "en": Localization(stringUnit: StringUnit(state: "translated", value: "Hi"))
                ]),
                "non_translatable": StringEntry(
                    shouldTranslate: false,
                    localizations: [
                        "en": Localization(stringUnit: StringUnit(
                            state: "translated", value: "API_KEY"))
                    ]
                ),
            ]
        )

        let untranslated = XCStringsReader(file: file).listUntranslated(for: "ja")
        #expect(untranslated == ["translatable"])
    }

    @Test func `checkCoverage reports 100% for shouldTranslate=false`() throws {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "translatable": StringEntry(localizations: [
                    "en": Localization(stringUnit: StringUnit(state: "translated", value: "Hi")),
                    "ja": Localization(stringUnit: StringUnit(state: "translated", value: "やあ")),
                ]),
                "non_translatable": StringEntry(
                    shouldTranslate: false,
                    localizations: [
                        "en": Localization(stringUnit: StringUnit(
                            state: "translated", value: "API_KEY"))
                    ]
                ),
            ]
        )
        let reader = XCStringsReader(file: file)

        let coverage = try reader.checkCoverage("non_translatable")
        #expect(coverage.coveragePercent == 100)
        #expect(coverage.missingLanguages.isEmpty)
    }

    @Test func `getStats excludes shouldTranslate=false from totals`() throws {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "a": StringEntry(localizations: [
                    "en": Localization(stringUnit: StringUnit(state: "translated", value: "A")),
                    "ja": Localization(stringUnit: StringUnit(state: "translated", value: "あ")),
                ]),
                "b": StringEntry(localizations: [
                    "en": Localization(stringUnit: StringUnit(state: "translated", value: "B"))
                ]),
                "non_translatable": StringEntry(
                    shouldTranslate: false,
                    localizations: [
                        "en": Localization(stringUnit: StringUnit(
                            state: "translated", value: "API_KEY"))
                    ]
                ),
            ]
        )

        let stats = XCStringsStatsCalculator(file: file).getStats()
        let ja = try #require(stats.coverageByLanguage["ja"])

        // Two translatable entries; one translated to ja → 50%. Without the filter this would be
        // 1/3 ≈ 33%.
        #expect(ja.total == 2)
        #expect(ja.translated == 1)
        #expect(ja.untranslated == 1)
        #expect(ja.coveragePercent == 50)
    }

    @Test func `getKey passes shouldTranslate through`() throws {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: ["non_translatable": StringEntry(shouldTranslate: false)]
        )

        let info = try XCStringsReader(file: file).getKey("non_translatable")
        #expect(info.shouldTranslate == false)
    }

    // MARK: - isCommentAutoGenerated

    @Test func `getKey passes isCommentAutoGenerated through`() throws {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "auto": StringEntry(
                    comment: "Auto-generated by Xcode",
                    isCommentAutoGenerated: true
                )
            ]
        )

        let info = try XCStringsReader(file: file).getKey("auto")
        #expect(info.isCommentAutoGenerated == true)
        #expect(info.comment == "Auto-generated by Xcode")
    }

    @Test func `isCommentAutoGenerated survives save load round trip`() throws {
        let json = """
            {
              "sourceLanguage" : "en",
              "strings" : {
                "auto" : {
                  "comment" : "Auto-generated by Xcode",
                  "isCommentAutoGenerated" : true
                }
              },
              "version" : "1.0"
            }
            """
        let data = Data(json.utf8)

        let decoded = try JSONDecoder().decode(XCStringsFile.self, from: data)
        #expect(decoded.strings["auto"]?.isCommentAutoGenerated == true)

        let reencoded = try XCStringsFileEncoder.encode(decoded)
        let redecoded = try JSONDecoder().decode(XCStringsFile.self, from: reencoded)
        #expect(redecoded.strings["auto"]?.isCommentAutoGenerated == true)
        #expect(redecoded.strings["auto"]?.comment == "Auto-generated by Xcode")
    }

    // MARK: - Xcode-style key sort

    @Test func `keys sort in UTF-8 byte order, not natural order`() {
        // xcstringstool puts uppercase before lowercase and "11_1" before "1_1"
        let expected = [
            "B upper", "Key10", "Key2", "b lower", "product.type.11_1", "product.type.12_1",
            "product.type.1_1", "product.type.2_1", "product.type.3_1",
        ]
        #expect(XCStringsKeySorter.sort(expected.reversed()) == expected)
    }

    @Test func `non-ASCII keys sort in UTF-8 byte order`() {
        // A decomposed "e" + U+0301 sorts with "e", and a precomposed U+00E9 sorts after "~".
        // Fullwidth forms and emoji sort after CJK because their UTF-8 lead bytes are larger.
        let expected = [
            "-x", "Z", "_x", "a", "e\u{301}b", "f", "~x", "\u{E9}", "\u{E9}a", "\u{3C9}",
            "\u{65E5}\u{672C}", "\u{FF41}", "\u{FF5E}", "\u{1F600}", "\u{1F600}x",
        ]
        #expect(XCStringsKeySorter.sort(expected.reversed()) == expected)
    }

    @Test func `listKeys uses Xcode sort`() {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: ["item_10": StringEntry(), "item_2": StringEntry(), "item_1": StringEntry()]
        )

        #expect(XCStringsReader(file: file).listKeys() == ["item_1", "item_10", "item_2"])
    }

    // MARK: - Encoder format

    @Test func `encoder does not escape forward slashes`() throws {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "category": StringEntry(localizations: [
                    "en": Localization(stringUnit: StringUnit(
                        state: "translated", value: "Domestic / Foreign"))
                ])
            ]
        )

        let data = try XCStringsFileEncoder.encode(file)
        // sm:ignore useFailableStringInit — encoder output is always valid UTF-8.
        let json = String(decoding: data, as: UTF8.self)

        #expect(json.contains("Domestic / Foreign"))
        #expect(!json.contains("\\/"))
    }

    // MARK: - NFKC suggestions

    @Test func `suggestions returns NFKC-equivalent existing keys`() {
        // Xcode-emitted key uses RIGHT SINGLE QUOTATION MARK (U+2019).
        let xcodeKey = "Record today\u{2019}s progress"
        let file = XCStringsFile(sourceLanguage: "en", strings: [xcodeKey: StringEntry()])
        let reader = XCStringsReader(file: file)

        // Caller passed the visually-identical APOSTROPHE (U+0027).
        let queried = "Record today\u{0027}s progress"
        #expect(reader.suggestions(for: queried) == [xcodeKey])
    }

    @Test func `keyNotFound includes NFKC suggestions in its description`() {
        let xcodeKey = "Record today\u{2019}s progress"
        let queried = "Record today\u{0027}s progress"
        let file = XCStringsFile(sourceLanguage: "en", strings: [xcodeKey: StringEntry()])

        do {
            _ = try XCStringsReader(file: file).getKey(queried)
            Issue.record("Expected keyNotFound to throw")
        } catch {
            let description = error.errorDescription ?? ""
            #expect(description.contains("Did you mean"))
            #expect(description.contains(xcodeKey))
        }
    }

    @Test func `suggestions are empty when no NFKC equivalent exists`() {
        let file = XCStringsFile(sourceLanguage: "en", strings: ["hello": StringEntry()])
        #expect(XCStringsReader(file: file).suggestions(for: "goodbye") == [])
    }

    // MARK: - Encoder format

    @Test func `encoder emits Xcode key-colon-value format with sorted keys`() throws {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "item_10": StringEntry(comment: "ten"), "item_2": StringEntry(comment: "two"),
            ]
        )

        let data = try XCStringsFileEncoder.encode(file)
        let json = String(decoding: data, as: UTF8.self)

        // Xcode uses `"key" : value` (space before colon), not `"key": value`.
        #expect(json.contains("\"sourceLanguage\" : \"en\""))
        // Byte order: item_10 comes before item_2.
        let idx2 = try #require(json.range(of: "\"item_2\""))
        let idx10 = try #require(json.range(of: "\"item_10\""))
        #expect(idx10.lowerBound < idx2.lowerBound)
        // Top-level shape: sourceLanguage, strings, version (in that order).
        let idxSrc = try #require(json.range(of: "\"sourceLanguage\""))
        let idxStrings = try #require(json.range(of: "\"strings\""))
        let idxVersion = try #require(json.range(of: "\"version\""))
        #expect(idxSrc.lowerBound < idxStrings.lowerBound)
        #expect(idxStrings.lowerBound < idxVersion.lowerBound)
    }

    @Test func `encoder writes empty objects and no trailing newline the way xcstringstool does`() throws {
        let file = XCStringsFile(
            strings: ["b": StringEntry(), "a": StringEntry(localizations: [:])]
        )

        let data = try XCStringsFileEncoder.encode(file)
        let json = String(decoding: data, as: UTF8.self)

        // An empty localizations object is left out, so "a" encodes as an empty object too.
        let expected = """
            {
              "sourceLanguage" : "en",
              "strings" : {
                "a" : {

                },
                "b" : {

                }
              },
              "version" : "1.0"
            }
            """
        #expect(json == expected)
        #expect(json.last == "}")
    }

    @Test func `encoder writes an empty strings object at its own indentation`() throws {
        let data = try XCStringsFileEncoder.encode(XCStringsFile())
        let json = String(decoding: data, as: UTF8.self)

        #expect(json.contains("\"strings\" : {\n\n  },"))
    }

    @Test func `encoder keeps a non-empty localizations object`() throws {
        let file = XCStringsFile(strings: [
            "key": StringEntry(localizations: [
                "en": Localization(stringUnit: StringUnit(state: "translated", value: "Hi"))
            ])
        ])

        let data = try XCStringsFileEncoder.encode(file)
        let decoded = try JSONDecoder().decode(XCStringsFile.self, from: data)

        #expect(decoded.strings["key"]?.localizations?["en"]?.stringUnit?.value == "Hi")
    }

    @Test func `encoder orders non-ASCII keys and language codes in UTF-8 byte order`() throws {
        let unit = Localization(stringUnit: StringUnit(state: "translated", value: "x"))
        let file = XCStringsFile(strings: [
            "\u{E9}": StringEntry(),
            "z": StringEntry(),
            "Z": StringEntry(localizations: ["zh-Hans": unit, "zh-HK": unit, "en": unit]),
        ])

        let data = try XCStringsFileEncoder.encode(file)
        let json = String(decoding: data, as: UTF8.self)

        func offset(of key: String) throws -> String.Index {
            try #require(json.range(of: "\"\(key)\" :")).lowerBound
        }
        #expect(try offset(of: "Z") < offset(of: "z"))
        #expect(try offset(of: "z") < offset(of: "\u{E9}"))
        #expect(try offset(of: "en") < offset(of: "zh-HK"))
        #expect(try offset(of: "zh-HK") < offset(of: "zh-Hans"))
    }

    // MARK: - checkUntranslated (Ryu0118/xcstrings-crud PR #33)

    @Test func `checkUntranslated flags missing localization`() {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "key": StringEntry(localizations: [
                    "en": Localization(stringUnit: StringUnit(state: "translated", value: "Hi"))
                ])
            ]
        )
        let issues = XCStringsReader(file: file).checkUntranslated(languages: ["ja"])
        #expect(issues.count == 1)
        #expect(issues[0].reason == .missingLocalization)
        #expect(issues[0].language == "ja")
        #expect(issues[0].key == "key")
    }

    @Test func `checkUntranslated flags empty value where listUntranslated misses`() {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "key": StringEntry(localizations: [
                    "en": Localization(stringUnit: StringUnit(state: "translated", value: "Hi")),
                    "ja": Localization(stringUnit: StringUnit(state: "translated", value: "")),
                ])
            ]
        )
        let reader = XCStringsReader(file: file)
        // Legacy tool silently accepts empty values as translated...
        #expect(reader.listUntranslated(for: "ja") == [])
        // ...but checkUntranslated catches them.
        let issues = reader.checkUntranslated(languages: ["ja"])
        #expect(issues.count == 1)
        #expect(issues[0].reason == .emptyValue)
    }

    @Test func `checkUntranslated flags non-translated state`() {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "key": StringEntry(localizations: [
                    "ja": Localization(stringUnit: StringUnit(state: "needs_review", value: "やあ"))
                ])
            ]
        )
        let issues = XCStringsReader(file: file).checkUntranslated(languages: ["ja"])
        #expect(issues.count == 1)
        #expect(issues[0].reason == .stateNotTranslated)
        #expect(issues[0].state == "needs_review")
    }

    @Test func `checkUntranslated flags empty plural variation value`() {
        let plural = PluralVariation(
            one: VariationValue(stringUnit: StringUnit(state: "translated", value: "1 item")),
            other: VariationValue(stringUnit: StringUnit(state: "translated", value: "")),
        )
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: [
                "count": StringEntry(localizations: [
                    "ja": Localization(variations: Variations(plural: plural))
                ])
            ]
        )
        let issues = XCStringsReader(file: file).checkUntranslated(languages: ["ja"])
        #expect(issues.count == 1)
        #expect(issues[0].reason == .emptyVariationValue)
    }

    @Test func `checkUntranslated skips shouldTranslate=false entries`() {
        let file = XCStringsFile(
            sourceLanguage: "en",
            strings: ["API_KEY": StringEntry(shouldTranslate: false, localizations: [:])]
        )
        let issues = XCStringsReader(file: file).checkUntranslated(languages: ["en", "ja"])
        #expect(issues.isEmpty)
    }
}
