import Foundation

/// Handles read operations for xcstrings files
public struct XCStringsReader: Sendable {
    private let file: XCStringsFile

    public init(file: XCStringsFile) { self.file = file }

    /// Get all keys sorted in Xcode's natural order.
    public func listKeys() -> [String] { XCStringsKeySorter.sort(file.strings.keys) }

    /// Find existing keys whose normalized form matches the queried key's
    /// normalized form. Surfaces visually-identical-but-Unicode-distinct
    /// substitutions like APOSTROPHE U+0027 vs RIGHT SINGLE QUOTATION MARK
    /// U+2019 (Xcode emits the latter in xcstrings keys like
    /// "Record today's progress"). Normalization is NFKC plus folding of
    /// curly quotes to their ASCII counterparts — pure NFKC does not unify
    /// the two apostrophe codepoints.
    public func suggestions(for key: String) -> [String] {
        let target = Self.normalizeForSuggestions(key)
        let matches = file.strings.keys.filter { existing in
            existing != key && Self.normalizeForSuggestions(existing) == target
        }
        return XCStringsKeySorter.sort(matches)
    }

    private static func normalizeForSuggestions(_ string: String) -> String {
        var folded = string.precomposedStringWithCompatibilityMapping
        let curlyToAscii: [Character: Character] = [
            "\u{2019}": "'",  // RIGHT SINGLE QUOTATION MARK
            "\u{2018}": "'",  // LEFT SINGLE QUOTATION MARK
            "\u{201C}": "\"", // LEFT DOUBLE QUOTATION MARK
            "\u{201D}": "\"", // RIGHT DOUBLE QUOTATION MARK
        ]
        folded = String(folded.map { curlyToAscii[$0] ?? $0 })
        return folded
    }

    /// Get all languages used in the file
    public func listLanguages() -> [String] {
        var languages = Set<String>()
        languages.insert(file.sourceLanguage)

        for entry in file.strings.values {
            if let localizations = entry.localizations { languages.formUnion(localizations.keys) }
        }

        return languages.sorted()
    }

    /// Get untranslated keys for a specific language. Skips entries marked
    /// `shouldTranslate: false` since those are intentionally not localized.
    public func listUntranslated(for language: String) -> [String] {
        var untranslated: [String] = []

        for (key, entry) in file.strings {
            guard entry.requiresTranslation else { continue }

            let isTranslated = entry.localizations?[language]?.stringUnit?.value != nil
                || entry.localizations?[language]?.variations != nil

            if !isTranslated { untranslated.append(key) }
        }

        return XCStringsKeySorter.sort(untranslated)
    }

    /// Get source language
    public func getSourceLanguage() -> String { file.sourceLanguage }

    /// Get key information
    public func getKey(_ key: String) throws(XCStringsError) -> KeyInfo {
        guard let entry = file.strings[key] else {
            throw XCStringsError.keyNotFound(key: key, suggestions: suggestions(for: key))
        }

        let languages = entry.localizations?.keys.sorted() ?? []

        return .init(
            key: key,
            comment: entry.comment,
            isCommentAutoGenerated: entry.isCommentAutoGenerated,
            extractionState: entry.extractionState,
            shouldTranslate: entry.shouldTranslate,
            languages: languages,
        )
    }

    /// Get translation for a key
    public func getTranslation(
        key: String,
        language: String?
    ) throws(XCStringsError) -> [String:
        TranslationInfo]
    {
        guard let entry = file.strings[key] else {
            throw XCStringsError.keyNotFound(key: key, suggestions: suggestions(for: key))
        }

        var result: [String: TranslationInfo] = [:]

        if let lang = language {
            if let localization = entry.localizations?[lang] {
                result[lang] = TranslationInfo(
                    key: key,
                    language: lang,
                    value: localization.stringUnit?.value,
                    state: localization.stringUnit?.state,
                    hasVariations: localization.variations != nil,
                )
            } else {
                throw XCStringsError.languageNotFound(language: lang, key: key)
            }
        } else {
            if let localizations = entry.localizations {
                for (lang, localization) in localizations {
                    result[lang] = TranslationInfo(
                        key: key,
                        language: lang,
                        value: localization.stringUnit?.value,
                        state: localization.stringUnit?.state,
                        hasVariations: localization.variations != nil,
                    )
                }
            }
        }

        return result
    }

    /// Check if a key exists
    public func checkKey(_ key: String, language: String?) -> Bool {
        guard let entry = file.strings[key] else { return false }

        if let lang = language { return entry.localizations?[lang] != nil }

        return true
    }

    /// List keys with extractionState == "stale" (potentially unused)
    public func listStaleKeys() -> [String] {
        let stale = file.strings.compactMap { key, entry in
            entry.extractionState == "stale" ? key : nil
        }
        return XCStringsKeySorter.sort(stale)
    }

    /// Check if multiple keys exist
    public func checkKeys(_ keys: [String], language: String?) -> [String: Bool] {
        var results: [String: Bool] = [:]
        for key in keys { results[key] = checkKey(key, language: language) }
        return results
    }

    /// Check coverage for a key. Non-translatable entries
    /// (`shouldTranslate: false`) report 100% coverage with no missing
    /// languages — they are intentionally untranslated.
    public func checkCoverage(_ key: String) throws(XCStringsError) -> CoverageInfo {
        let allLanguages = listLanguages()

        guard let entry = file.strings[key] else {
            throw XCStringsError.keyNotFound(key: key, suggestions: suggestions(for: key))
        }

        guard entry.requiresTranslation else {
            return .init(
                key: key,
                translatedLanguages: [],
                missingLanguages: [],
                coveragePercent: 100,
            )
        }

        let translatedLanguages = entry.localizations?.keys.sorted() ?? []
        let missingLanguages = allLanguages.filter { !translatedLanguages.contains($0) }
        let coveragePercent = allLanguages.isEmpty
            ? 0
            : Double(translatedLanguages.count) / Double(allLanguages.count) * 100

        return .init(
            key: key,
            translatedLanguages: translatedLanguages,
            missingLanguages: missingLanguages,
            coveragePercent: coveragePercent,
        )
    }
}
